name: Build Tag

on:
  push:
    tags:        
      - v**

env:
  NODE_VERSION: '16.14.0'

jobs:
  Build-tag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        registry-url: https://registry.npmjs.org/
        cache: 'yarn'
    - run: yarn install
    - run: yarn run build:tag
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}